# -----------------------------------------------------------------------------
# Alacritty configuration
# -----------------------------------------------------------------------------

[general]
import = [
  "keybinds.toml",
  "style.toml",
  "theme.toml",
]

[terminal]
shell = { program = "zellij", args = [ "-l", "welcome" ] }
