# -----------------------------------------------------------------------------
# Alacritty configuration
# -----------------------------------------------------------------------------

[general]
import = [
  "keybinds.toml",
  "style.toml",
  "theme.toml",
]
