# -----------------------------------------------------------------------------
# Alacritty style settings
# -----------------------------------------------------------------------------

# [font]
# offset = { x = 0, y = 0 }
# glyph_offset = { x = 0, y = 0 }
# size = 12

[font.normal]
style = "Regular"
# family = "AdwaitaMono Nerd Font"
# family = "CaskaydiaCove Nerd Font"
family = "CaskaydiaMono Nerd Font"
# family = "JetBrainsMono Nerd Font"
# family = "RobotoMono Nerd Font"

[colors]
draw_bold_text_with_bright_colors = true

[window]
startup_mode = "Maximized"
dynamic_padding = true
padding = { x = 10, y = 10 }
blur = true
opacity = 0.8
