[font]
# size = 12
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[colors]
draw_bold_text_with_bright_colors = true

[window]
startup_mode = "Maximized"
dynamic_padding = true
padding = { x = 10, y = 10 }
blur = true
opacity = 0.8
